"""initial schema

Revision ID: 28da758fcd10
Revises: 
Create Date: 2026-07-18 16:53:27.105857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28da758fcd10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_code'), 'games', ['code'], unique=True)
    op.create_table('game_configs',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('num_reels', sa.SmallInteger(), nullable=False),
    sa.Column('num_rows', sa.SmallInteger(), nullable=False),
    sa.Column('target_rtp', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('min_bet', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_bet', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('bet_step', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'version', name='uq_game_config_version')
    )
    op.create_table('sessions',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_configs',
    sa.Column('game_config_id', sa.Uuid(), nullable=False),
    sa.Column('feature_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_config_id'], ['game_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_config_id', 'feature_type', name='uq_feature_type_per_config')
    )
    op.create_table('paylines',
    sa.Column('game_config_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('positions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_config_id'], ['game_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_config_id', 'index', name='uq_payline_index_per_config')
    )
    op.create_table('simulation_runs',
    sa.Column('game_config_id', sa.Uuid(), nullable=False),
    sa.Column('num_spins', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_config_id'], ['game_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_game_config_id'), 'simulation_runs', ['game_config_id'], unique=False)
    op.create_table('spin_records',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('game_config_id', sa.Uuid(), nullable=False),
    sa.Column('bet_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_bonus_buy', sa.Boolean(), nullable=False),
    sa.Column('feature_buy_id', sa.String(length=64), nullable=True),
    sa.Column('grid', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('win_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('win_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('features_triggered', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rng_proof', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_config_id'], ['game_configs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spin_records_game_config_id'), 'spin_records', ['game_config_id'], unique=False)
    op.create_index(op.f('ix_spin_records_session_id'), 'spin_records', ['session_id'], unique=False)
    op.create_table('symbols',
    sa.Column('game_config_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol_type', sa.String(length=16), nullable=False),
    sa.Column('wild_subtype', sa.String(length=16), nullable=True),
    sa.Column('reel_weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('paytable', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_config_id'], ['game_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_config_id', 'code', name='uq_symbol_code_per_config')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbols')
    op.drop_index(op.f('ix_spin_records_session_id'), table_name='spin_records')
    op.drop_index(op.f('ix_spin_records_game_config_id'), table_name='spin_records')
    op.drop_table('spin_records')
    op.drop_index(op.f('ix_simulation_runs_game_config_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_table('paylines')
    op.drop_table('feature_configs')
    op.drop_table('sessions')
    op.drop_table('game_configs')
    op.drop_index(op.f('ix_games_code'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
