"""add symbol multiplier_value

Revision ID: e5e23f02939c
Revises: ef31a325aa6d
Create Date: 2026-07-21 10:47:01.147513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e23f02939c'
down_revision: Union[str, Sequence[str], None] = 'ef31a325aa6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('multiplier_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'multiplier_value')
    # ### end Alembic commands ###
