"""add symbol tier and game_config bet_steps

Revision ID: ea2ef9677bec
Revises: 28da758fcd10
Create Date: 2026-07-18 18:04:30.870471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea2ef9677bec'
down_revision: Union[str, Sequence[str], None] = '28da758fcd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_configs', sa.Column('bet_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('symbols', sa.Column('tier', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'tier')
    op.drop_column('game_configs', 'bet_steps')
    # ### end Alembic commands ###
