"""add symbol max_per_reel

Revision ID: ef31a325aa6d
Revises: ea2ef9677bec
Create Date: 2026-07-19 16:08:59.668196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef31a325aa6d'
down_revision: Union[str, Sequence[str], None] = 'ea2ef9677bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('max_per_reel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'max_per_reel')
    # ### end Alembic commands ###
