"""Bridges the slot-builder wizard's Stage 3 (grid size + selected mechanics)
to a real, simulatable `GameConfig` — without this, finishing the wizard only
produces assets/layout, never a game the engine can actually spin (TZ's whole
point of the builder is a new slot without a developer hand-writing a
`app/seed/*.py`-style config).

Generated numbers are deliberately simple, industry-typical *placeholders*
(same spirit as the app/seed/*.py demo games' own docstrings) — not
RTP-tuned. The admin is expected to simulate and tune via the existing
draft/simulate/publish flow (app/api/admin/service.py) before publishing.
"""

from decimal import Decimal

from app.api.v1.response_builders import avalanche_out
from app.services.config_adapter import to_paylines, to_reel_set_config
from app.services.grid_format import to_frontend_grid
from app.services.spin_features import apply_expanding_wild, apply_reel_caps
from app.engine.avalanche import run_avalanche
from app.engine.reels import spin_reels
from app.engine.rng import RNGProvider
from app.engine.wins import evaluate_spin
from app.models.config import FeatureConfig, GameConfig, Payline, Symbol
from app.models.enums import FeatureType, GameConfigStatus, SymbolType, WildSubtype
from app.models.game import Game

# Notes-field marker so a later `generate-config` call can tell "still our
# untouched auto-generated draft, safe to replace" apart from anything a
# human has since edited or published (service.py checks this).
AUTO_NOTE_PREFIX = "Auto-generated by the slot builder wizard"

DEFAULT_TARGET_RTP = 0.96
DEFAULT_BET_STEPS = [10_000, 25_000, 50_000, 100_000, 250_000, 500_000]

_LOW_CODES_WEIGHTS = [("low_a", 24), ("low_b", 20), ("low_c", 18), ("low_d", 16)]
_HIGH_CODES_WEIGHTS = [("high_a", 8), ("high_b", 6)]


def _bet_steps_for(rows: int) -> list[int]:
    """/api/v1's validate_bet_amount rejects any bet_amount not evenly
    divisible by the payline count, and this generator always lays down one
    straight payline per row (see the Payline loop below) — so num_paylines
    == rows. DEFAULT_BET_STEPS alone only happens to satisfy that for a few
    row counts (e.g. 5); round each step up to the nearest multiple of rows
    so every real spin actually clears validation regardless of the Stage 3
    grid size chosen."""
    def round_up(value: int) -> int:
        remainder = value % rows
        return value if remainder == 0 else value + (rows - remainder)
    return [round_up(step) for step in DEFAULT_BET_STEPS]


def _scaled_paytable(reels: int, top_value: float, growth: float = 2.5) -> dict[str, float]:
    """Match-count paytable for an arbitrary reel count: highest achievable
    count (== `reels`) pays `top_value`, each count below it divides by
    `growth` — a generic stand-in for the curated 3/4/5 tables the demo
    games hand-tune (TZ §14 leaves exact paytables an open question)."""
    min_count = min(3, reels) if reels >= 3 else max(1, reels)
    counts = list(range(min_count, reels + 1))
    return {str(c): round(top_value / (growth ** i), 2) for i, c in enumerate(reversed(counts))}


# app/seed/party_of_goods.py's exact thresholds (8/10/12/15) are ratios of
# its 6x5=30-cell board, not fixed engine constants (app/engine/avalanche.py's
# _best_tier does a generic max-key-<=-count lookup over whatever paytable
# dict it's given) — scaling these ratios to reels*rows keeps the "how much
# of the board" difficulty roughly constant for any grid size.
_AVALANCHE_THRESHOLD_RATIOS = [4 / 15, 1 / 3, 2 / 5, 1 / 2]
_AVALANCHE_LOW_TIER_VALUES = [0.5, 1, 2, 5]
_AVALANCHE_HIGH_TIER_VALUES = [1, 2.5, 5, 15]


def _avalanche_tier_thresholds(reels: int, rows: int) -> list[int]:
    total_cells = reels * rows
    thresholds = sorted({max(2, round(total_cells * ratio)) for ratio in _AVALANCHE_THRESHOLD_RATIOS})
    return thresholds


def _avalanche_paytable(thresholds: list[int], values: list[float]) -> dict[str, float]:
    # values has exactly len(_AVALANCHE_THRESHOLD_RATIOS) entries; thresholds
    # may have fewer after dedup on a small board — align from the end so
    # the biggest threshold always keeps its biggest payout.
    return dict(zip((str(t) for t in thresholds), values[-len(thresholds):]))


def _generate_avalanche_config(
    game: Game, reels: int, rows: int, mechanics_set: set[str], symbol_assets: list[dict]
) -> GameConfig:
    """Party-of-goods-style cascade config: count-anywhere tiered payouts
    instead of paylines (app/engine/avalanche.py replaces evaluate_spin
    entirely — see run_builder_test_spin's own avalanche branch below and
    spin_avalanche.py in production), a bomb symbol that clears its row+
    column every step it lands, and (if coin_multiplier is also picked)
    multiplier tokens that add into the cascade's running multiplier."""
    config = GameConfig(
        game=game,
        version=1,
        status=GameConfigStatus.DRAFT.value,
        num_reels=reels,
        num_rows=rows,
        target_rtp=DEFAULT_TARGET_RTP,
        min_bet=DEFAULT_BET_STEPS[0],
        max_bet=DEFAULT_BET_STEPS[-1],
        bet_step=DEFAULT_BET_STEPS[0],
        # No payline-divisibility constraint to satisfy here — avalanche has
        # zero Payline rows, and validate_bet_amount skips the divisibility
        # check entirely when num_paylines == 0.
        bet_steps=DEFAULT_BET_STEPS,
        notes=(
            f"{AUTO_NOTE_PREFIX} from grid {reels}x{rows} + mechanics {sorted(mechanics_set)} — "
            "placeholder math (industry-typical shapes, not RTP-tuned). Simulate and tune before publish."
        ),
    )

    order = 0

    def add_symbol(code: str, name: str, symbol_type: str, tier: str, weight: int, pays: dict, **kwargs) -> None:
        nonlocal order
        image_ref = symbol_assets[order]["id"] if order < len(symbol_assets) else None
        Symbol(
            game_config=config, code=code, name=name, symbol_type=symbol_type, tier=tier,
            reel_weights=[weight] * reels, paytable=pays, display_order=order, image_ref=image_ref, **kwargs,
        )
        order += 1

    thresholds = _avalanche_tier_thresholds(reels, rows)
    low_pays = _avalanche_paytable(thresholds, _AVALANCHE_LOW_TIER_VALUES)
    high_pays = _avalanche_paytable(thresholds, _AVALANCHE_HIGH_TIER_VALUES)

    for code, weight in _LOW_CODES_WEIGHTS:
        add_symbol(code, code.replace("_", " ").title(), SymbolType.REGULAR.value, "low", weight, low_pays)
    for code, weight in _HIGH_CODES_WEIGHTS:
        add_symbol(code, code.replace("_", " ").title(), SymbolType.REGULAR.value, "high", weight, high_pays)

    # Substitute-only, same as party-of-goods — never count-pays on its own.
    add_symbol("wild", "Wild", SymbolType.WILD.value, "high", 2, {})

    needs_scatter = "scatter" in mechanics_set or "free_spins" in mechanics_set
    if needs_scatter:
        add_symbol("scatter", "Scatter", SymbolType.SCATTER.value, "low", 2, {}, max_per_reel=1)

    # Board-clearing bomb — what makes an avalanche board actually cascade
    # down to nothing, not gated behind its own checkbox.
    add_symbol("boom", "Boom", SymbolType.BONUS.value, "low", 1, {}, is_bomb=True)

    if "coin_multiplier" in mechanics_set:
        for code, value in (("x2", 2), ("x3", 3), ("x5", 5), ("x7", 7)):
            add_symbol(code, code.upper(), SymbolType.BONUS.value, "low", 2, {}, multiplier_value=value)

    add_feature_order = 0

    def add_feature(feature_type: str, params: dict, enabled: bool = True) -> None:
        nonlocal add_feature_order
        FeatureConfig(game_config=config, feature_type=feature_type, enabled=enabled,
                      params=params, display_order=add_feature_order)
        add_feature_order += 1

    add_feature(FeatureType.AVALANCHE.value, {"multiplier_steps": [1, 2, 3, 5], "max_cascades": 20})

    if "free_spins" in mechanics_set:
        add_feature(FeatureType.FREE_SPINS.value, {
            "trigger_symbol_code": "scatter",
            "trigger_count": 3,
            "spins_awarded_by_count": {"3": 8, "4": 10, "5": 12},
            "retrigger_enabled": True,
            "win_multiplier": 1,
        })
    if "bonus_buy" in mechanics_set:
        # Avalanche has no hold_and_win-compatible target — free_spins only.
        target_available = "free_spins" in mechanics_set
        add_feature(
            FeatureType.BONUS_BUY.value,
            {"buy_id": "bonus_buy", "cost_multiplier": 100, "target_feature_id": "free_spins"},
            enabled=target_available,
        )
    if "gamble" in mechanics_set:
        add_feature(FeatureType.GAMBLE.value, {"mode": "color", "max_rounds": 5})
    if "jackpot" in mechanics_set:
        add_feature(FeatureType.JACKPOT.value, {
            "levels": [{"weight": 50, "value_multiplier": 50}, {"weight": 5, "value_multiplier": 500}],
            "odds_denominator": 1_000_000,
        })

    return config


def generate_default_config(
    game: Game, reels: int, rows: int, mechanics: list[str], symbol_assets: list[dict] | None = None
) -> GameConfig:
    """symbol_assets is the builder manifest's assets.images filtered to
    category=="symbol" (each {"id":..., "file":...}), assigned to the
    synthesized symbols below in display order — first uploaded image goes
    to the first symbol, and so on. Fewer uploads than symbol slots (up to
    8: 4 low + 2 high + wild + optional scatter/coin/collector) just leaves
    the remaining symbols' image_ref None; the frontend player falls back to
    a placeholder for those. None/empty list means no real art at all yet,
    same as before this parameter existed."""
    mechanics_set = set(mechanics)
    symbol_assets = symbol_assets or []

    if "avalanche" in mechanics_set:
        return _generate_avalanche_config(game, reels, rows, mechanics_set, symbol_assets)

    bet_steps = _bet_steps_for(rows)
    config = GameConfig(
        game=game,
        version=1,
        status=GameConfigStatus.DRAFT.value,
        num_reels=reels,
        num_rows=rows,
        target_rtp=DEFAULT_TARGET_RTP,
        min_bet=bet_steps[0],
        max_bet=bet_steps[-1],
        bet_step=bet_steps[0],
        bet_steps=bet_steps,
        notes=(
            f"{AUTO_NOTE_PREFIX} from grid {reels}x{rows} + mechanics {sorted(mechanics_set)} — "
            "placeholder math (industry-typical shapes, not RTP-tuned). Simulate and tune before publish."
        ),
    )

    order = 0

    def add_symbol(code: str, name: str, symbol_type: str, tier: str, weight: int, pays: dict, **kwargs) -> None:
        nonlocal order
        image_ref = symbol_assets[order]["id"] if order < len(symbol_assets) else None
        Symbol(
            game_config=config, code=code, name=name, symbol_type=symbol_type, tier=tier,
            reel_weights=[weight] * reels, paytable=pays, display_order=order, image_ref=image_ref, **kwargs,
        )
        order += 1

    for code, weight in _LOW_CODES_WEIGHTS:
        add_symbol(code, code.replace("_", " ").title(), SymbolType.REGULAR.value, "low", weight,
                   _scaled_paytable(reels, 10))
    for code, weight in _HIGH_CODES_WEIGHTS:
        add_symbol(code, code.replace("_", " ").title(), SymbolType.REGULAR.value, "high", weight,
                   _scaled_paytable(reels, 50))

    add_symbol(
        "wild", "Wild", SymbolType.WILD.value, "high", 1, _scaled_paytable(reels, 150),
        wild_subtype=WildSubtype.EXPANDING.value if "expanding_wild" in mechanics_set else None,
    )

    needs_scatter = "scatter" in mechanics_set or "free_spins" in mechanics_set
    if needs_scatter:
        add_symbol("scatter", "Scatter", SymbolType.SCATTER.value, "low", 3,
                   _scaled_paytable(reels, 50), max_per_reel=1)

    needs_coin = "hold_and_win" in mechanics_set or "coin_multiplier" in mechanics_set
    if needs_coin:
        add_symbol("coin", "Coin", SymbolType.BONUS.value, "low", 4, {})
    if "coin_multiplier" in mechanics_set:
        add_symbol("collector", "Collector", SymbolType.BONUS.value, "low", 2, {})

    # One straight payline per row — the simplest layout that's always valid
    # for any reels x rows combination (TZ §14: exact count/layout is an open
    # question; richer zigzag lines are something to add by hand later).
    for row in range(rows):
        Payline(game_config=config, index=row + 1, positions=[row] * reels)

    feature_order = 0

    def add_feature(feature_type: str, params: dict, enabled: bool = True) -> None:
        nonlocal feature_order
        FeatureConfig(game_config=config, feature_type=feature_type, enabled=enabled,
                      params=params, display_order=feature_order)
        feature_order += 1

    min_count = min(3, reels) if reels >= 3 else max(1, reels)

    if "free_spins" in mechanics_set:
        counts = range(min_count, reels + 1)
        add_feature(FeatureType.FREE_SPINS.value, {
            "trigger_symbol_code": "scatter",
            "trigger_count": min_count,
            "spins_awarded_by_count": {str(c): 5 + 2 * (c - min_count) for c in counts},
            "retrigger_enabled": True,
            "win_multiplier": 1,
        })
    if "expanding_wild" in mechanics_set:
        add_feature(FeatureType.EXPANDING_WILD.value, {
            "trigger_symbol_code": "wild", "walk_enabled": True, "walk_direction": "right",
        })
    if "hold_and_win" in mechanics_set:
        add_feature(FeatureType.HOLD_AND_WIN.value, {
            "trigger_symbol_code": "coin", "trigger_count": min(6, reels * rows), "respin_count": 3,
        })
    if "coin_multiplier" in mechanics_set:
        add_feature(FeatureType.COIN_MULTIPLIER.value, {
            "coin_symbol_code": "coin", "collector_symbol_code": "collector",
        })
    if "gamble" in mechanics_set:
        add_feature(FeatureType.GAMBLE.value, {"mode": "color", "max_rounds": 5})
    if "jackpot" in mechanics_set:
        add_feature(FeatureType.JACKPOT.value, {
            "levels": [{"weight": 50, "value_multiplier": 50}, {"weight": 5, "value_multiplier": 500}],
            "odds_denominator": 1_000_000,
        })
    if "bonus_buy" in mechanics_set:
        target = "free_spins" if "free_spins" in mechanics_set else "hold_and_win" if "hold_and_win" in mechanics_set else None
        add_feature(
            FeatureType.BONUS_BUY.value,
            # buy_id is what a client passes as FeatureBuyRequest.feature_id
            # (app/api/v1/bonus_buy.py's resolve_bonus_buy_product) — without
            # it this flat single-product shape can never be matched/bought.
            {"buy_id": "bonus_buy", "cost_multiplier": 100, "target_feature_id": target or "free_spins"},
            enabled=target is not None,
        )

    return config


def run_builder_test_spin(config: GameConfig, rng: RNGProvider) -> dict:
    """One ad-hoc spin against a builder-generated config (Stage 5 "test this
    slot"), reusing the exact same pure engine calls as production
    (app/api/v1/spin_service.py) and the RTP simulator (app/simulator/engine.py)
    — but for a single spin with full grid/win detail, and no Session/
    SpinRecord persistence. That last part matters here specifically: this
    config is a DRAFT (service.py's draft/publish workflow keeps drafts out
    of `/api/v1/session/start`'s reach on purpose), so a real player session
    could never spin it — this is the only way to see it actually spin
    before publishing.

    No free-spins/hold-and-win orchestration either way — enough to prove
    the generated config is structurally spinnable; the admin config
    editor's simulator is the tool for real RTP/volatility numbers over many
    spins.
    """
    reel_set = to_reel_set_config(config)
    bet_amount = Decimal(str(config.min_bet))

    avalanche_config = next(
        (fc for fc in config.feature_configs if fc.feature_type == "avalanche" and fc.enabled), None
    )
    if avalanche_config is not None:
        grid = spin_reels(reel_set, rng)
        grid = apply_reel_caps(grid, reel_set, rng)
        params = avalanche_config.params
        result = run_avalanche(
            grid, reel_set, reel_set.symbols, rng, bet_amount,
            multiplier_steps=params.get("multiplier_steps", [1]),
            max_cascades=params.get("max_cascades", 20),
        )
        return {
            "bet_amount": int(bet_amount),
            "grid": to_frontend_grid(grid),
            "total_win": int(result.total_win),
            "line_wins": [],
            "count_wins": [],
            "avalanche": avalanche_out(result).model_dump(),
        }

    paylines = to_paylines(config)
    bet_per_line = bet_amount / Decimal(len(paylines)) if paylines else bet_amount

    grid = spin_reels(reel_set, rng)
    grid = apply_reel_caps(grid, reel_set, rng)

    wild_config = next(
        (fc for fc in config.feature_configs if fc.feature_type == "expanding_wild" and fc.enabled), None
    )
    apply_expanding_wild(grid, wild_config, {}, rng, bet_amount, reel_set)

    evaluation = evaluate_spin(grid, reel_set.symbols, paylines, bet_per_line, bet_amount)

    return {
        "bet_amount": int(bet_amount),
        "grid": [list(column) for column in grid.reels],
        "total_win": int(evaluation.total_win),
        "line_wins": [
            {"payline": w.payline_index, "symbol": w.symbol_code, "count": w.count, "amount": int(w.win_amount)}
            for w in evaluation.line_wins
        ],
        "count_wins": [
            {"symbol": w.symbol_code, "count": w.count, "amount": int(w.win_amount)}
            for w in evaluation.count_wins
        ],
    }
